<div id="<?php echo $this->getWrapperId();?>">
<?php echo $this->getChildHtml('', false);?>
</div>
<script type="text/javascript">
new EcomDev.Varnish.AjaxBlock({
    container: '<?php echo $this->getWrapperId();?>',
    block: '<?php echo $this->getBlockName();?>',
    cookie: '<?php echo $this->getCookie();?>',
    callback: <?php echo $this->getCallback() ? $this->getCallback() : 'false' ?>
});
</script>