<script src="<?php echo $this->getJsUrl('ecomdev/varnish.bundle.js');?>" async></script>

<style>
.ecomdev-varnish-placeholder { display: inline; padding: 0; margin: 0; }
</style>

<script type="ecomdev/varnish-element" data-type="block-loader">
<?php echo $this->helper('core')->jsonEncode(['url' => $this->helper('ecomdev_varnish')->getAjaxReloadUrl()]);?>
</script>

<script type="ecomdev/varnish-element" data-type="page-info">
<?php echo $this->helper('core')->jsonEncode($this->helper('ecomdev_varnish')->getCurrentPageInfo()) ?>
</script>
