<script type="text/javascript">
window.ecomdevVarnishScope = function (action) {
    if (!window.EcomDev || !EcomDev.Varnish) {
        setTimeout(
            function () { window.ecomdevVarnishScope(action); },
            5
        );
    } else {
        action();
    }
};

window.currentPage = <?php
    echo $this->helper('core')->jsonEncode(Mage::helper('ecomdev_varnish')->getCurrentPageInfo()) 
?>;

ecomdevVarnishScope(function () {
    EcomDev.Varnish.AjaxBlock.url = <?php echo $this->helper('core')->jsonEncode(
        $this->helper('ecomdev_varnish')->getAjaxReloadUrl()
    );?>;
});
</script>
